# Generated by Django 4.1 on 2022-08-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_worker',
            field=models.BooleanField(default=False),
        ),
    ]
