# Generated by Django 4.1 on 2022-08-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_company_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_worker',
            new_name='company_owner',
        ),
    ]
