# Generated by Django 4.1 on 2022-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_store_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(),
        ),
    ]
