# Generated by Django 4.1 on 2022-08-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_managers'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='sore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
            preserve_default=False,
        ),
    ]
