# Generated by Django 4.1 on 2022-08-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='posta',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.address'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('purchase_order_number', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('deliver_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.address')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.supplier')),
            ],
        ),
    ]
