# Generated by Django 4.1 on 2022-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchaseorder_items_purchaseorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
