# Generated by Django 4.1 on 2022-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseorder_sore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='sore',
            new_name='store',
        ),
    ]
