# Generated by Django 4.1 on 2022-08-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_store_company'),
        ('purchase', '0003_rename_sore_purchaseorder_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
    ]
