# Generated by Django 4.1 on 2022-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchaseorder_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='branch',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='deliver_to',
            field=models.TextField(),
        ),
    ]
