# Generated by Django 4.1 on 2022-08-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_remove_purchaseorder_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='store',
        ),
    ]
