# Generated by Django 4.1 on 2022-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_purchaseorder_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
