# Generated by Django 4.1 on 2022-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseorder_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='received',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('TRANSIT', 'TRANSIT'), ('RECEIVED', 'RECEIVED')], default='TRANSIT', max_length=100),
        ),
    ]
