# Generated by Django 4.1 on 2022-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
