# Generated by Django 4.1 on 2022-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='SKU_number',
            field=models.CharField(max_length=100),
        ),
    ]
