# Generated by Django 4.1 on 2022-08-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('Inventory', '0002_alter_store_address_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.address')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='Preferred_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.supplier'),
        ),
    ]
