# Generated by Django 4.1 on 2022-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_seling_price_item_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enough',
            field=models.BooleanField(default=True),
        ),
    ]
