# Generated by Django 4.1 on 2022-09-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_managers'),
        ('inventory', '0005_supplier_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
