# Generated by Django 4.1 on 2022-09-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_supplier_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='company_name',
        ),
    ]
