# Generated by Django 4.1 on 2022-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salesorder_items_salesorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
