# Generated by Django 4.1 on 2022-08-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_supplier_alter_item_preferred_supplier'),
        ('Sales', '0002_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_ordered_items', to='Inventory.item'),
        ),
    ]
