# Generated by Django 4.1 on 2022-08-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='branch',
            field=models.CharField(max_length=255),
        ),
    ]
