# Generated by Django 4.1 on 2022-08-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='branch',
        ),
    ]
