# Generated by Django 4.1 on 2022-09-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_managers'),
        ('sales', '0004_remove_salesorder_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
            preserve_default=False,
        ),
    ]
