# Generated by Django 4.1 on 2022-09-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
