# Generated by Django 4.1 on 2022-09-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
