# Generated by Django 4.1 on 2022-09-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_supplier_company_name'),
        ('sales', '0008_rename_customer_name_salesorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='inventory.item'),
        ),
    ]
