# Generated by Django 4.1 on 2022-09-05 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_salesorder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
